### ISSUE TITLE
Add climate data to the project folder

### ISSUE THREAD

**Issue by SebastianJL** [SebastianJL/Climate#1]
The csv file with the climate data of the different cities should be uploaded to the project folder.

**Comment by SebastianJL** [comment]
@PascalSiemon 
Ich schrieb der da nomal de Ordner uf:
ch.uzh.ifi.climate.public

**Comment by PascalSiemon** [comment]
@SebastianJL "public" isch es Wort wo ned akzeptiert wird... Package heisst jetzt ch.uzh.ifi.climate.data

**Comment by SebastianJL** [comment]
whut? Wieso wird das nöd akzeptiert?

**Comment by PascalSiemon** [comment]
"Invalid package name. 'public' is not a valid Java identifier"

**Comment by PascalSiemon** [comment]
Uploaded .csv file to ch.uzh.ifi.climate.data (Filename = "GlobalLandTemperaturesByMajorCity_v1.csv", Path = "/Climate/src/ch/uzh/ifi/climate/data/GlobalLandTemperaturesByMajorCity_v1.csv")
Changes in comparison to the original file: Added the correct special characters (ô,ã,...)

**Comment by SebastianJL** [comment]
hans jetzt au grad agluet. mega strange wemmer sich mal die [site uf gwt](http://www.gwtproject.org/doc/latest/DevGuideOrganizingProjects.html)  aluegt.
(Eifach mit ctl+f nach public sueche, s zweite suechergebnis)
