### ISSUE TITLE
Filters which are already in the flextable shouldn't be added again

### ISSUE THREAD

**Issue by CarmenChristen** [SebastianJL/Climate#14]
Test if the filter input is already in the flextable and if yes, do not add it again.
Do this in the Climate.java class.

**Comment by PascalSiemon** [comment]
@CarmenChristen Possible solution: Change the stuff in the filtering class, that just the right ArrayList will be returned. So for the table visualization you would just need to reload the whole thing with the corrected ArrayList :)
If you like this solution I could implement it
