### ISSUE TITLE
Client Side Basics

### ISSUE THREAD

**Issue by SebastianJL** [SebastianJL/Climate#3]
Write the code to display some dummy message on the webpage.
Something along the lines of "UNDER CONSTRUCTION Come back later to see our awesome app."

You need to fill the following files for this:
- src.ch.uzh.ifi.climate.client.Climate.java (the entry point class for the climate app)
- war/Climate.html (The host HTML page that loads the Climate app)
- maybe others

**Comment by PascalSiemon** [comment]
@davwys Hi
