### ISSUE TITLE
Implement QueryServiceImpl

### ISSUE THREAD

**Issue by SebastianJL** [SebastianJL/Climate#7]

**Comment by PascalSiemon** [comment]
Finished QueryServiceImpl (not tested yet)
Should return an ArrayList<TemperatureMeasurement> with the filtered measurements.

@SebastianJL Unknown problem with 
import com.google.appengine.repackaged.com.google.protobuf.TextFormat.Parser;
(besides that import there is no error anymore)

**Comment by PascalSiemon** [comment]
Done.
